YooKassa: YooKassa
Stripe: Stripe
Type: Type
PayOption: Pay option
PaymentOption: Payment option
PayOptions: Pay options
PaymentOptions: Payment options
SearchEngineOptimization: Search Engine Optimization
Booking: Booking
Schedule: Schedule
BasicEntities: Basic Entities
SecretKey: Secret key
PublicKey: Public key
PaymentGateway: Payment gateway
ClientSecret: Client secret
ClientId: Client id
Username: Username
Available: Available
Duration: Duration
PaymentIntent: Payment intent
Canceled: Canceled
Error: Error
MicrocopyPayAtVenue: Pay after the service is provided 
MicrocopyPayNow: Pay using a credit card or PayPal
MicrocopySelectPayAtVenue: Select this option if you intend to pay after the service is provided 
MicrocopySelectPayNow: Select this option if you intend to make an online payment using a credit card, PayPal, or other payment method
Unknown: Unknown
Paid: Paid
Unpaid: Unpaid
Role: Role
Priority: Priority
Name: Name
TheAppointment: Appointment
Location: Location
BookingDetails: Booking details
EmployeeWorkScheduleForThisMonthNotSetYet: It seems that the employee's work schedule for this month has not yet been set
NoServicesWereFoundForSearchTerms: No services were found containing all your search terms
UseCaseDiagram: Use Case Diagram
StateMachineDiagram: State machine diagram
NoEmployeesAvailableNow: No employees are available for appointments at this time
Previous: Previous
EmployeeScheduleNotGeneratedYet: Employee schedule is not yet generated
FillFromPreviousMonth: Fill in from previous month
FillFromWorkingSchedule: Fill in from the working schedule
WorkSchedule: Schedule
SymbolMinute: min
SymbolHour: h
Day: Day
EndTime: End time
StartTime: Start time
WorkingHours: Working hours
UnitMinutes: minutes
SchedulingInterval: Scheduling interval
SelectAvailableDayAndTimePlease: Please select the available day and time for the appointment
AppointmentSetFor: Appointment set for
SelectTime: Select time
Select: Select
Sun: Sun
Sat: Sat
Fri: Fri
Thu: Thu
Wed: Wed
Tue: Tue
Mon: Mon
ViewBookingDetails: View booking details
ReturnToHomePage: Return to Home Page
YourBookingHasBeenCreatedSuccessfully: Your booking has been created successfully
Finish: Finish
Price: Price
Currency: Currency
TimeZone: Time zone
SourceCode: Source code
Resources: Resources
Overview: Overview
IssueTracking: Issue tracking
Documentation: Documentation
ErDiagram: ER Diagram
PaymentStatus: Payment status
SomethingWentWrong: Something went wrong
PaymentSuccessfullyCompleted: Payment successfully completed
PaymentIntentCancelled: Payment intent was cancelled
Pay: Pay
PaymentAmount: Payment amount
Checkout: Checkout
PayNow: Pay now
PayAtVenue: Pay at venue
PaymentMethod: Payment method
AppointmentTime: Appointment time
BookAService: Book a service
Next: Next
ServicesToBook: Services to book
MakeAnAppointment: Make an appointment
WelcomeTo: Welcome to
TheStart: Start
AssignmentDate: Assignment Date
ServiceAssignment: Assignment
Description: Description
Service: Service
Services: Services
ServiceAssignments: Assignments
Employee: Employee
Phone: Phone
Mobile: Mobile
Staff: Staff
AlreadyExists: Already exists
Workspace: Workspace
Address: Address
Workspaces: Workspaces
Details: Details
RecordAdded: Record added
Business: Business
Owner: Owner
TheName: Name
Add: Add
YouMightWantToAddAFew: You might want to add a few
ThereAreNoDataYet: There are no data yet
NoDataYet: No data yet
Businesses: Businesses
Attribution: Attribution
SuperuserCannotBeDeleted: Superuser cannot be deleted
NotSpecified: Not specified
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Dele: Delete
Email: Email
Google: Google
No: No
Verified: Verified
VerificationKey: Verification key
Yes: Yes
User: User
NoUsersYet: There are no users yet
NotIndicated: Not indicated
Birthday: Birthday
FullName: Full name
Cancel: Cancel
Save: Save
Edit: Edit
Account: Account
PersonalInfo: Personal info
InvalidUrlOrRemoved: Invalid URL or resource removed
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
GoogleSecretManager: Google Secret Manager
GmailAccount: Gmail account
Cleared: Cleared
InvalidFormData: Invalid form data
RecordDeleted: Record deleted
ClearSettings: Clear
RecordEdited: Record edited
InvalidStoreType: Invalid store type
StoreType: Store type
Database: Database
UserSession: User session
Initialize: Initialize
Tokens: Tokens
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
AnotherAccountAccessProhibited: Access to another user's account is prohibited
Authentication: Authentication
PasswordRecovery: Password recovery
CreatePassword: Create password
EmailVerification: Email verification
VerifyEmailPlease: Please verify your email
JustSentEmailTo: We just sent an email to
ClickToVerifyAccount: Click the link in the email to verify your account
DidNotGetEmail: Didn't receive the email?
ResendEmail: Resend email
Back: Back
Registration: Registration
Or: or
ForgotYourPassword: Forgot your password?
DoNotHaveAnAccount: Don't have an account?
CreateAccount: Create account
EmailAddress: Email address
Password: Password
DemoUserAccounts: Demo user accounts
Superuser: Superuser
Administrator: Administrator
ThankYou: Thank you
VerifyYourEmailAddress: Verify your email address
ConfirmEmailPlease: Please confirm your email address by clicking on the link below
GmailAccountNotSet: Gmail account is not set. Initialize tokens.
SignInWithGoogle: Sign in with Google
SignIn: Sign in
SignOut: Sign out
UserAccount: User account
Photo: Photo
Data: Data
MainMenu: Main menu
Users: Users
Welcome: Welcome
AppDocumentation: App documentation
AppDescription: Online bookings for services and appointments
AppName: Reservare

Doc001 appname@Text href@Text: <a href=#{href} target=_blank>“#{appname}”</a> allows businesses to register services and resources that a customer can book and/or schedule an appointment for.

Doc002 href@Text: <a href=#{href} target=_blank>Project repository</a> on GitHub.

Doc003 href@Text: Please note that the application currently running is a demo application. Any actions are allowed and encouraged. <a href=#{href} target=_blank>Report issues</a> on GitHub.

Doc004: A superuser account is defined at deployment time. The superuser manages other users and grants or revokes administrator privileges to specific users.

Doc005: Integration with external APIs

Doc006 href1@Text href2@Text: A new user can <a href=#{href1} target=_blank>sign up</a> using an existing Google account or using a verified email address. <a href=#{href2} target=_blank>Gmail API</a> is used as an intermediary to send verification links to the user's inbox.

Doc007: A user can be grated the administrator role by a superuser or by another administrator. Only users with the administrator role have access to administrative data.

Doc008 href@Text: To simulate a successful payment, use test cards from the <a href=#{href}>following list</a>.

Doc009 href@Text: To simulate payments that the issuer declines, use test cards from the <a href=#{href}>following list</a>.