ServiceAssignments: Assignments
Employee: Employee
Phone: Phone
Mobile: Mobile
Staff: Staff
AlreadyExists: Already exists
Workspace: Workspace
Address: Address
Workspaces: Workspaces
Details: Details
RecordAdded: Record added
Business: Business
Owner: Owner
TheName: Name
Add: Add
YouMightWantToAddAFew: You might want to add a few
ThereAreNoDataYet: There are no data yet
NoDataYet: No data yet
Businesses: Businesses
Attribution: Attribution
SuperuserCannotBeDeleted: Superuser cannot be deleted
NotSpecified: Not specified
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Dele: Delete
Email: Email
Google: Google
No: No
Verified: Verified
VerificationKey: Verification key
Yes: Yes
User: User
NoUsersYet: There are no users yet
NotIndicated: Not indicated
Birthday: Birthday
FullName: Full name
Cancel: Cancel
Save: Save
Edit: Edit
Account: Account
PersonalInfo: Personal info
InvalidUrlOrRemoved: Invalid URL or resource removed
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
GoogleSecretManager: Google Secret Manager
GmailAccount: Gmail account
Cleared: Cleared
InvalidFormData: Invalid form data
RecordDeleted: Record deleted
ClearSettings: Clear
RecordEdited: Record edited
InvalidStoreType: Invalid store type
StoreType: Store type
Database: Database
UserSession: User session
Initialize: Initialize
Tokens: Tokens
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
AnotherAccountAccessProhibited: Access to another user's account is prohibited
Authentication: Authentication
PasswordRecovery: Password recovery
CreatePassword: Create password
EmailVerification: Email verification
VerifyEmailPlease: Please verify your email
JustSentEmailTo: We just sent an email to
ClickToVerifyAccount: Click the link in the email to verify your account
DidNotGetEmail: Didn't receive the email?
ResendEmail: Resend email
Back: Back
Registration: Registration
Or: or
ForgotYourPassword: Forgot your password?
DoNotHaveAnAccount: Don't have an account?
CreateAccount: Create account
EmailAddress: Email address
Password: Password
DemoUserAccounts: Demo user accounts
Superuser: Superuser
Administrator: Administrator
ThankYou: Thank you
VerifyYourEmailAddress: Verify your email address
ConfirmEmailPlease: Please confirm your email address by clicking on the link below
GmailAccountNotSet: Gmail account is not set. Initialize tokens.
SignInWithGoogle: Sign in with Google
SignIn: Sign in
SignOut: Sign out
UserAccount: User account
Photo: Photo
Data: Data
MainMenu: Main menu
Users: Users
Welcome: Welcome
AppName: Reservare