
Authentication: Authentication
PasswordRecovery: Password recovery
CreatePassword: Create password
EmailVerification: Email verification
VerifyEmailPlease: Please verify your email
JustSentEmailTo: We just sent an email to
ClickToVerifyAccount: Click the link in the email to verify your account
DidNotGetEmail: Didn't receive the email?
ResendEmail: Resend email
Back: Back
Registration: Registration
Or: or
ForgotYourPassword: Forgot your password?
DoNotHaveAnAccount: Don't have an account?
CreateAccount: Create account
EmailAddress: Email address
Password: Password
DemoUserAccounts: Demo user accounts
Superuser: Superuser
Administrator: Administrator
ThankYou: Thank you
VerifyYourEmailAddress: Verify your email address
ConfirmEmailPlease: Please confirm your email address by clicking on the link below
GmailAccountNotSet: Gmail account is not set. Initialize tokens.
SignInWithGoogle: Sign in with Google
SignIn: Sign in
SignOut: Sign out
UserAccount: User account
Photo: Photo
Data: Data
MainMenu: Main menu
Users: Users
Welcome: Welcome
AppName: Reservare