
Authentication: Authentification
PasswordRecovery: Récupération de mot de passe
CreatePassword: Créer un mot de passe
EmailVerification: Vérification de l'E-mail
VerifyEmailPlease: Veuillez vérifier votre email
JustSentEmailTo: Nous venons d'envoyer un email à
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
ResendEmail: Ré-envoyer l'email
Back: Retour
Registration: Inscription
Or: ou
ForgotYourPassword: Mot de passe oublié?
DoNotHaveAnAccount: Vous n'avez pas de compte ?
CreateAccount: Créer un compte
EmailAddress: Adresse e-mail
Password: Mot de passe
DemoUserAccounts: Comptes d'utilisateurs démo
Superuser: Superutilisateur
Administrator: Administrateur
ThankYou: Merci
VerifyYourEmailAddress: Vérifiez votre adresse e-mail
ConfirmEmailPlease: Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous
GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
SignInWithGoogle: Connectez-vous avec Google
SignIn: Se connecter
SignOut: Se déconnecter
UserAccount: Compte d'utilisateur
Photo: Photo
Data: Donnés
MainMenu: Menu principal
Users: Utilisateurs
Welcome: Bienvenu
AppName: Reservare