AssignmentDate: Date d'affectation
ServiceAssignment: Affectation
Description: Description
Service: Service
Services: Services
ServiceAssignments: Affectations
Employee: Employée
Phone: Téléphone
Mobile: Mobile
Staff: Personelle
AlreadyExists: Existe déjà
Workspace: Espace de travail
Address: Adresse
Workspaces: Espaces de travail
Details: Détails
RecordAdded: Enregistrement ajouté
Business: Entreprise
Owner: Propriétaire
TheName: Nom
Add: Ajouter
YouMightWantToAddAFew: Vous voudrez peut-être en ajouter quelques-uns
ThereAreNoDataYet: Il n'y a pas encore de données
NoDataYet: Pas encore de données
Businesses: Entreprises
Attribution: Attribution
SuperuserCannotBeDeleted: Le superutilisateur ne peut pas être supprimé
NotSpecified: Not specified
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer ?
ConfirmPlease: Veuillez confirmer
Dele: Supprimer
Email: E-mail
Google: Google
No: Non
Verified: Vérifié
VerificationKey: Clé de vérification
Yes: Oui
User: Utilisateur
NoUsersYet: Il n'y a pas encore d'utilisateurs
NotIndicated: Non indiqué
Birthday: Date de naissance
FullName: Nom et prénom
Cancel: Annuler
Save: Enregistrer
Edit: Modifier
Account: Compte
PersonalInfo: Données personnelles
InvalidUrlOrRemoved: URL invalide ou ressource supprimée
BackToHomepage: Retournez à la page d'accueil
InvalidArguments: Arguments invalides
PermissionDenied: Permission refusée
PageNotFound: Page non trouvée
GoogleSecretManager: Google Secret Manager
GmailAccount: Compte Gmail
Cleared: Effacé
InvalidFormData: Données de formulaire incorrectes
RecordDeleted: L'enregistrement a été supprimé
ClearSettings: Effacer
RecordEdited: L'enregistrement a été modifié
InvalidStoreType: Type de stockage invalide
StoreType: Type de stockage
Database: Base de données
UserSession: Session utilisateur
Initialize: Initialiser
Tokens: Jetons
AccessDeniedAdminsOnly: Seuls les administrateurs ont accès à cette page. Veuillez vous connecter avec un compte administrateur
LoginPlease: Veuillez vous connecter pour accéder à cette page
AnotherAccountAccessProhibited: L'accès au compte d'un autre utilisateur est interditx
Authentication: Authentification
PasswordRecovery: Récupération de mot de passe
CreatePassword: Créer un mot de passe
EmailVerification: Vérification de l'E-mail
VerifyEmailPlease: Veuillez vérifier votre email
JustSentEmailTo: Nous venons d'envoyer un email à
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
ResendEmail: Ré-envoyer l'email
Back: Retour
Registration: Inscription
Or: ou
ForgotYourPassword: Mot de passe oublié?
DoNotHaveAnAccount: Vous n'avez pas de compte ?
CreateAccount: Créer un compte
EmailAddress: Adresse e-mail
Password: Mot de passe
DemoUserAccounts: Comptes d'utilisateurs démo
Superuser: Superutilisateur
Administrator: Administrateur
ThankYou: Merci
VerifyYourEmailAddress: Vérifiez votre adresse e-mail
ConfirmEmailPlease: Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous
GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
SignInWithGoogle: Connectez-vous avec Google
SignIn: Se connecter
SignOut: Se déconnecter
UserAccount: Compte d'utilisateur
Photo: Photo
Data: Donnés
MainMenu: Menu principal
Users: Utilisateurs
Welcome: Bienvenu
AppName: Reservare