Group: Groupe
Tabs: Onglets
Subsector: Sous-secteur
Subsectors: Sous-secteurs
Sector: Secteur
Sectors: Secteurs
WorkspaceWithoutPaymentOptions: Espace de travail sans options de paiement
NoPaymentOptionSpecified: Aucune option de paiement spécifiée
PaymentDeclined: Paiement refusé
ShopId: ID de la boutique
Payments: Paiements
NoPaymentsHaveBeenMadeYet: Aucun paiement n'a encore été effectué
TotalCharge: Charge totale
InvalidPaymentAmount: Montant du paiement incorrect
UnhandledError: Erreur non gérée
PaymentGatewayNotSpecified: Passerelle de paiement non spécifiée
Icon: Icône
YooKassa: YooKassa
Stripe: Stripe
Type: Type
PayOption: Modalité de paiement
PaymentOption: Modalité de paiement
PayOptions: Options de paiement
PaymentOptions: Options de paiement
SearchEngineOptimization: Optimisation du moteur de recherche
Booking: Réservation
Schedule: Horaire de travail
BasicEntities: Entités de base
SecretKey: Clé secrète
PublicKey: Clé publique
PaymentGateway: Passerelle de paiement
ClientSecret: Secret client
ClientId: Identifiant client
Username: Nom d'utilisateur
Available: Disponible
Duration: Durée
PaymentIntent: L'intention de paiement
Canceled: Annulé
Error: Erreur
MicrocopyPayAtVenue: Payer après la prestation du service
MicrocopyPayNow: Payez avec une carte de crédit ou PayPal
MicrocopySelectPayAtVenue: Sélectionnez cette option si vous avez l'intention de payer une fois le service fourni
MicrocopySelectPayNow: Sélectionnez cette option si vous avez l'intention d'effectuer un paiement en ligne en utilisant une carte de crédit, PayPal ou un autre mode de paiement
Unknown: Inconnu
Paid: Payé
Unpaid: Non payé
Role: Rôle
Priority: Priorité
Name: Nom
TheAppointment: Le Rendez-vous
Location: Emplacement
BookingDetails: Les détails de réservation
EmployeeWorkScheduleForThisMonthNotSetYet: Il semble que l'horaire de travail du salarié pour ce mois-ci n'ait pas encore été fixé
NoServicesWereFoundForSearchTerms: Aucun service contenant tous vos termes de recherche n'a été trouvé
UseCaseDiagram: Diagramme de cas d'utilisation
StateMachineDiagram: Diagramme de machine d'état
NoEmployeesAvailableNow: Aucun employé n'est disponible pour un rendez-vous pour le moment
Previous: Précédent
EmployeeScheduleNotGeneratedYet: L'horaire des employés n'est pas encore généré
FillFromPreviousMonth: Remplissez du mois précédent
FillFromWorkingSchedule: Remplissez à partir de l'horaire de travail
WorkSchedule: Horaire de travail
SymbolMinute: min
SymbolHour: h
Day: Jour
EndTime: Heure de fin
StartTime: Heure de début
WorkingHours: Heures d'ouverture
UnitMinutes: minutes
SchedulingInterval: Intervalle de planification
SelectAvailableDayAndTimePlease: Veuillez sélectionner le jour et l'heure disponibles pour le rendez-vous
AppointmentSetFor: Rendez-vous fixé au
SelectTime: Sélectionnez l'heure
Select: Sélectionner
Sun: dim.
Sat: sam.
Fri: ven.
Thu: jeu.
Wed: mer.
Tue: mar.
Mon: lun.
ViewBookingDetails: Afficher les détails de la réservation
ReturnToHomePage: Retour à la page d'accueil
YourBookingHasBeenCreatedSuccessfully: Votre réservation a été créée avec succès
Finish: Finir
Price: Prix
Currency: Devise
TimeZone: Fuseau horaire
SourceCode: Code source
Resources: Ressources
Overview: Aperçu
IssueTracking: Signalement de bogues
Documentation: Documentation
ErDiagram: Diagramme ER
PaymentStatus: Statut de paiement
SomethingWentWrong: Quelque chose n'a pas fonctionné
PaymentSuccessfullyCompleted: Paiement effectué avec succès
PaymentIntentCancelled: L'intention de paiement a été annulée
Pay: Payez
PaymentAmount: Montant du paiement
Checkout: Vérifier
PayNow: Payez maintenant
PayAtVenue: Paiement sur place
PaymentMethod: Mode de paiement
AppointmentTime: Heure de rendez-vous
BookAService: Réserver une prestation
Next: Suivante
ServicesToBook: Services à réserver
MakeAnAppointment: Prendre rendez-vous
WelcomeTo: Bienvenue sur
TheStart: Le début
AssignmentDate: Date d'affectation
ServiceAssignment: Affectation
Description: Description
Service: Service
Services: Services
ServiceAssignments: Affectations
Employee: Employée
Phone: Téléphone
Mobile: Mobile
Staff: Personelle
AlreadyExists: Existe déjà
Workspace: Espace de travail
Address: Adresse
Workspaces: Espaces de travail
Details: Détails
RecordAdded: Enregistrement ajouté
Business: Entreprise
Owner: Propriétaire
TheName: Nom
Add: Ajouter
YouMightWantToAddAFew: Vous voudrez peut-être en ajouter quelques-uns
ThereAreNoDataYet: Il n'y a pas encore de données
NoDataYet: Pas encore de données
Businesses: Entreprises
Attribution: Attribution
SuperuserCannotBeDeleted: Le superutilisateur ne peut pas être supprimé
NotSpecified: Not specified
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer ?
ConfirmPlease: Veuillez confirmer
Dele: Supprimer
Email: E-mail
Google: Google
No: Non
Verified: Vérifié
VerificationKey: Clé de vérification
Yes: Oui
User: Utilisateur
NoUsersYet: Il n'y a pas encore d'utilisateurs
NotIndicated: Non indiqué
Birthday: Date de naissance
FullName: Nom et prénom
Cancel: Annuler
Save: Enregistrer
Edit: Modifier
Account: Compte
PersonalInfo: Données personnelles
InvalidUrlOrRemoved: URL invalide ou ressource supprimée
BackToHomepage: Retournez à la page d'accueil
InvalidArguments: Arguments invalides
PermissionDenied: Permission refusée
PageNotFound: Page non trouvée
GoogleSecretManager: Google Secret Manager
GmailAccount: Compte Gmail
Cleared: Effacé
InvalidFormData: Données de formulaire incorrectes
RecordDeleted: L'enregistrement a été supprimé
ClearSettings: Effacer
RecordEdited: L'enregistrement a été modifié
InvalidStoreType: Type de stockage invalide
StoreType: Type de stockage
Database: Base de données
UserSession: Session utilisateur
Initialize: Initialiser
Tokens: Jetons
AccessDeniedAdminsOnly: Seuls les administrateurs ont accès à cette page. Veuillez vous connecter avec un compte administrateur
LoginPlease: Veuillez vous connecter pour accéder à cette page
AnotherAccountAccessProhibited: L'accès au compte d'un autre utilisateur est interditx
Authentication: Authentification
PasswordRecovery: Récupération de mot de passe
CreatePassword: Créer un mot de passe
EmailVerification: Vérification de l'E-mail
VerifyEmailPlease: Veuillez vérifier votre email
JustSentEmailTo: Nous venons d'envoyer un email à
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
ResendEmail: Ré-envoyer l'email
Back: Retour
Registration: Inscription
Or: ou
ForgotYourPassword: Mot de passe oublié?
DoNotHaveAnAccount: Vous n'avez pas de compte ?
CreateAccount: Créer un compte
EmailAddress: Adresse e-mail
Password: Mot de passe
DemoUserAccounts: Comptes d'utilisateurs démo
Superuser: Superutilisateur
Administrator: Administrateur
ThankYou: Merci
VerifyYourEmailAddress: Vérifiez votre adresse e-mail
ConfirmEmailPlease: Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous
GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
SignInWithGoogle: Connectez-vous avec Google
SignIn: Se connecter
SignOut: Se déconnecter
UserAccount: Compte d'utilisateur
Photo: Photo
Data: Donnés
MainMenu: Menu principal
Users: Utilisateurs
Welcome: Bienvenu
AppDocumentation: Documentation de l'application
AppDescription: Réservations en ligne de prestations et de rendez-vous
AppName: Reservare

Doc001 appname href: <a href=#{href} target=_blank>« #{appname} »</a> permet aux entreprises d'enregistrer des services et des ressources pour lesquels un client peut réserver et/ou prendre rendez-vous.

Doc002 href: <a href=#{href} target=_blank>Le référentiel du projet</a> sur GitHub.

Doc003 href: Veuillez noter que l'application actuellement en cours d'exécution est une application de démonstration. Toutes les actions sont autorisées et encouragées. <a href=#{href} target=_blank>Signalez les bugs</a> sur GitHub.

Doc004: Un compte superutilisateur est défini au moment du déploiement. Le superutilisateur gère les autres utilisateurs et accorde ou révoque les privilèges d'administrateur à des utilisateurs spécifiques.

Doc005: Intégration avec des API externes

Doc006 href1 href2: Un nouvel utilisateur peut <a href=#{href1} target=_blank>s'inscrire</a> en utilisant un compte Google existant ou en utilisant une adresse e-mail vérifiée. <a href=#{href2} target=_blank>L'API Gmail</a> est utilisée comme intermédiaire pour envoyer des liens de vérification vers la boîte de réception de l'utilisateur.

Doc007: Un utilisateur peut se voir attribuer le rôle d'administrateur par un superutilisateur ou par un autre administrateur. Seuls les utilisateurs disposant du rôle d'administrateur ont accès aux données administratives.

Doc008 href: Pour simuler un paiement réussi, utilisez les cartes de test de la <a href=#{href}>liste suivante</a>.

Doc009 href: Pour simuler les paiements refusés par l'émetteur, utilisez les cartes de test de la <a href=#{href}>liste suivante</a>.

Doc010: Pour chaque espace de travail, vous pouvez spécifier une ou plusieurs options de paiement en sélectionnant son type, son nom et sa passerelle de paiement.

Doc011: Si plusieurs passerelles de paiement sont configurées pour un espace de travail, elles seront présentées comme options à l'utilisateur qui réserve le rendez-vous.

Doc012: Si un espace de travail n'a qu'une seule option de paiement (passerelle de paiement) configurée, elle sera alors utilisée par défaut et représentera ainsi une étape de moins dans le processus de réservation.

Doc013: Au moins une option de paiement (passerelle de paiement) doit être spécifiée pour l'espace de travail. Si aucune option n'est spécifiée, une erreur se produira lors de la réservation.

Doc014: Un secteur représente le type d’activité du service fourni. Principalement utilisé comme clés de recherche pour les services.

Doc015: Si nécessaire, une hiérarchie de ces secteurs peut être définie.