Authentication: Autentificare
PasswordRecovery: Recuperarea parolei
CreatePassword: Creează parolă
EmailVerification: Verificare a email-ului
VerifyEmailPlease: Vă rugăm să vă verificați e-mailul
JustSentEmailTo: Tocmai am trimis un e-mail la
ClickToVerifyAccount: Faceți clic pe linkul din e-mail pentru a vă verifica contul
DidNotGetEmail: Nu aţi primit e-mailul?
ResendEmail: Retrimiteți e-mailul
Back: Înapoi
Registration: Înregistrare
Or: sau
ForgotYourPassword: Ați uitat parola?
DoNotHaveAnAccount: Nu aveți cont?
CreateAccount: Creează-ți un cont
EmailAddress: Adresa de e-mail
Password: Parola
DemoUserAccounts: Conturi de utilizator Demo
Superuser: Superutilizator
Administrator: Administrator
ThankYou: Vă mulțumim
VerifyYourEmailAddress: Verifică-ți adresa de email
ConfirmEmailPlease: Vă rugăm să confirmați adresa dvs. de e-mail făcând clic pe link-ul de mai jos
GmailAccountNotSet: Contul Gmail nu este setat. Inițializați jetoanele.
SignInWithGoogle: Conectați-vă cu Google
SignIn: Conectați-vă
SignOut: Deconectați-vă
UserAccount: Cont de utilizator
Photo: Foto
Data: Date
MainMenu: Meniu principal
Users: Utilizatori
Welcome: Bine ați venit
AppName: Reservare