Error: Eroare
MicrocopyPayAtVenue: Plătiți după prestarea serviciului
MicrocopyPayNow: Plătiți folosind un card de credit sau PayPal
MicrocopySelectPayAtVenue: Selectați această opțiune dacă intenționați să plătiți după furnizarea serviciului
MicrocopySelectPayNow: Selectați această opțiune dacă intenționați să efectuați o plată online folosind un card de credit, PayPal sau altă metodă de plată
Unknown: Necunoscut
Paid: Plătit
Unpaid: Neplătit
Role: Rol
Priority: Prioritate
Name: Numele
TheAppointment: Întâlnirea
Location: Locația
BookingDetails: Detaliile rezervării
EmployeeWorkScheduleForThisMonthNotSetYet: Se pare că programul de lucru al angajatului pentru această lună nu a fost încă stabilit
NoServicesWereFoundForSearchTerms: Nu au fost găsite servicii care să conțină toți termenii dvs. de căutare
UseCaseDiagram: Diagrama cazurilor de utilizare
StateMachineDiagram: Diagrama mașinii de stare
NoEmployeesAvailableNow: Nu există angajați disponibili pentru programări în acest moment
Previous: Precedent
EmployeeScheduleNotGeneratedYet: Programul angajatului nu a fost încă generat
FillFromPreviousMonth: Completați din luna precedentă
FillFromWorkingSchedule: Completați din programul de lucru
WorkSchedule: Orarul de lucru
SymbolMinute: min
SymbolHour: h
Day: Ziua
EndTime: Ora de încheiere
StartTime: Ora de începere
WorkingHours: Ore de lucru
UnitMinutes: minute
SchedulingInterval: Interval de programare
SelectAvailableDayAndTimePlease: Vă rugăm să selectați ziua și ora disponibile pentru întâlnire
AppointmentSetFor: Întâlnirea stabilită pentru
SelectTime: Selectați ora
Select: Selectează
Sun: dum.
Sat: sâm.
Fri: vin.
Thu: joi
Wed: mie.
Tue: mar.
Mon: lun.
ViewBookingDetails: Vizualizați detaliile rezervării
ReturnToHomePage: Înapoi la pagina de start
YourBookingHasBeenCreatedSuccessfully: Rezervarea dvs. a fost creată cu succes
Finish: Finalizare
Price: Preț
Currency: Valuta
TimeZone: Fusul orar
SourceCode: Codul sursă
Resources: Resurse
Overview: Prezentare generală
IssueTracking: Raportarea erorilor
Documentation: Documentație
ErDiagram: Diagrama ER
PaymentStatus: Starea plății
SomethingWentWrong: Ceva n-a mers bine
PaymentSuccessfullyCompleted: Plata a fost finalizată cu succes
PaymentIntentCancelled: Intenția de plată a fost anulată
Pay: Plătiți
PaymentAmount: Suma de plată
Checkout: Verifică
PayNow: Plătiți acum
PayAtVenue: Plata la locatie
PaymentMethod: Modalitate de plată
AppointmentTime: Ora întâlnirii
BookAService: Rezervați un serviciu
Next: Urmatorul
ServicesToBook: Servicii de rezervat
MakeAnAppointment: Faceți o programare
WelcomeTo: Bine ați venit la
TheStart: Începutul
AssignmentDate: Data atribuirii
ServiceAssignment: Atribuție
Description: Descriere
Service: Serviciu
Services: Servicii
ServiceAssignments: Atribuții
Employee: Angajat
Phone: Telefon
Mobile: Mobil
Staff: Personal
AlreadyExists: Deja exista
Workspace: Spațiu de lucru
Address: Adresa
Workspaces: Spații de lucru
Details: Detalii
RecordAdded: Înregistrare adăugată
Business: Afacere
Owner: Proprietar
TheName: Numele
Add: Adaugă
YouMightWantToAddAFew: Poate doriți să adăugați câteva
ThereAreNoDataYet: Nu există date încă
NoDataYet: Nu există date încă
Businesses: Afaceri
Attribution: Atribuire
SuperuserCannotBeDeleted: Superutilizatorul nu poate fi șters
NotSpecified: Nespecificat
DeleteAreYouSure: Sigur doriți să ștergeți?
ConfirmPlease: Vă rugăm să confirmați
Dele: Șterge
Email: E-mail
Google: Google
No: Nu
Verified: Verificat
VerificationKey: Cheia de verificare
Yes: Da
User: Utilizator
NoUsersYet: Nu există încă utilizatori
NotIndicated: Nu este indicat
Birthday: Ziua de naștere
FullName: Numele complet
Cancel: Renunță
Save: Salvează
Edit: Editează
Account: Contul
PersonalInfo: Date personale
InvalidUrlOrRemoved: Adresă URL nevalidă sau resursă eliminată
BackToHomepage: Reveniți la pagina de pornire
InvalidArguments: Argumente nevalide
PermissionDenied: Acces refuzat
PageNotFound: Pagina nu a fost găsită
GoogleSecretManager: Google Secret Manager
GmailAccount: Cont Gmail
Cleared: S-a șters
InvalidFormData: Date de formular nevalide
RecordDeleted: Înregistrarea a fost ștearsă
ClearSettings: Ștergeți
RecordEdited: Înregistrarea a fost editată
InvalidStoreType: Tip de stocare nevalid
StoreType: Tipul de stocare
Database: Baza de date
UserSession: Sesiunea de utilizator
Initialize: Inițializează
Tokens: Jetoane
AccessDeniedAdminsOnly: Doar administratorii au acces la această pagină. Vă rugăm să vă conectați cu un cont de administrator
LoginPlease: Vă rugăm să vă conectați pentru a accesa această pagină
AnotherAccountAccessProhibited: Accesul la contul altui utilizator este interzis
Authentication: Autentificare
PasswordRecovery: Recuperarea parolei
CreatePassword: Creează parolă
EmailVerification: Verificare a email-ului
VerifyEmailPlease: Vă rugăm să vă verificați e-mailul
JustSentEmailTo: Tocmai am trimis un e-mail la
ClickToVerifyAccount: Faceți clic pe linkul din e-mail pentru a vă verifica contul
DidNotGetEmail: Nu aţi primit e-mailul?
ResendEmail: Retrimiteți e-mailul
Back: Înapoi
Registration: Înregistrare
Or: sau
ForgotYourPassword: Ați uitat parola?
DoNotHaveAnAccount: Nu aveți cont?
CreateAccount: Creează-ți un cont
EmailAddress: Adresa de e-mail
Password: Parola
DemoUserAccounts: Conturi de utilizator Demo
Superuser: Superutilizator
Administrator: Administrator
ThankYou: Vă mulțumim
VerifyYourEmailAddress: Verifică-ți adresa de email
ConfirmEmailPlease: Vă rugăm să confirmați adresa dvs. de e-mail făcând clic pe link-ul de mai jos
GmailAccountNotSet: Contul Gmail nu este setat. Inițializați jetoanele.
SignInWithGoogle: Conectați-vă cu Google
SignIn: Conectați-vă
SignOut: Deconectați-vă
UserAccount: Cont de utilizator
Photo: Foto
Data: Date
MainMenu: Meniu principal
Users: Utilizatori
Welcome: Bine ați venit
AppDocumentation: Documentația aplicației
AppDescription: Rezervări online pentru servicii și programări
AppName: Reservare

Doc001 appname href: <a href=#{href} target=_blank>„#{appname}”</a> permite companiilor să înregistreze servicii și resurse pentru care un client le poate rezerva și/sau programa o întâlnire.

Doc002 href: <a href=#{href} target=_blank>Depozitul de proiect</a> pe GitHub.

Doc003 href: Vă rugăm să rețineți că aplicația care rulează în prezent este o aplicație demonstrativă. Orice acțiune este permisă și încurajată. <a href=#{href} target=_blank>Raportați erori</a> pe GitHub.