NoStaffAssignedYet: Для этой услуги пока не назначен ни один сотрудник
Registrant: Регистрант
OwnerName: Имя владельца
BookNow: Забронировать сейчас
Book: Забронировать
Catalog: Каталог
Catalogue: Каталог
ServiceCatalog: Каталог услуг
Roles: Роли
Group: Группа
Tabs: Вкладки
Subsector: Подсектор
Subsectors: Подсекторы
Sector: Сектор
Sectors: Сектора
WorkspaceWithoutPaymentOptions: Рабочее пространство без вариантов оплаты
NoPaymentOptionSpecified: Не указан вариант оплаты
PaymentDeclined: Платеж отклонен
ShopId: Идентификатор магазина
Payments: Платежи
NoPaymentsHaveBeenMadeYet: Платежи пока не производились
TotalCharge: Общая стоимость
InvalidPaymentAmount: Неверная сумма платежа
UnhandledError: Необработанная ошибка
PaymentGatewayNotSpecified: Платежный шлюз не указан
Icon: Значок
YooKassa: ЮKassa
Stripe: Stripe
Type: Тип
PayOption: Вариант оплаты
PaymentOption: Вариант оплаты
PayOptions: Варианты оплаты
PaymentOptions: Варианты оплаты
SearchEngineOptimization: Поисковая оптимизация
Booking: Бронирование
Schedule: График работы
BasicEntities: Основные сущности
SecretKey: Секретный ключ
PublicKey: Открытый ключ
PaymentGateway: Платежный шлюз
ClientSecret: Секрет клиента
ClientId: Идентификатор клиента
Username: Имя пользователя
Available: Доступный
Duration: Продолжительность
PaymentIntent: Намерение платежа
Canceled: Отменено
Error: Ошибка
MicrocopyPayAtVenue: Оплата после оказания услуги
MicrocopyPayNow: Оплата с помощью кредитной карты или PayPal
MicrocopySelectPayAtVenue: Выберите этот вариант, если вы планируете платить после оказания услуги
MicrocopySelectPayNow: Выберите этот вариант, если вы собираетесь совершить онлайн-платеж с помощью кредитной карты, PayPal или другого способа оплаты
Unknown: Неизвестно
Paid: Оплачено
Unpaid: Не оплачено
Role: Роль
Priority: Приоритет
Name: Имя
TheAppointment: Встреча
Location: Местонахождение
BookingDetails: Детали бронирования
EmployeeWorkScheduleForThisMonthNotSetYet: Похоже, график работы сотрудника на этот месяц еще не установлен
NoServicesWereFoundForSearchTerms: Не найдено ни одной услуги, содержащей все ваши условия поиска
UseCaseDiagram: Диаграмма вариантов использования
StateMachineDiagram: Схема машины состояний
NoEmployeesAvailableNow: В настоящее время нет сотрудников для записи на прием
Previous: Предыдущий
EmployeeScheduleNotGeneratedYet: График работы сотрудников еще не сформирован
FillFromPreviousMonth: Заполнить с предыдущего месяца
FillFromWorkingSchedule: Заполнить из графика работы
WorkSchedule: График работы
SymbolMinute: мин
SymbolHour: ч
Day: День
EndTime: Время окончания
StartTime: Время начала
WorkingHours: Рабочее время
UnitMinutes: минуты
SchedulingInterval: Интервал планирования
SelectAvailableDayAndTimePlease: Пожалуйста, выберите свободный день и время для записи
AppointmentSetFor: Встреча назначена на
SelectTime: Выберите время
Select: Выбирать
Sun: вс
Sat: сб
Fri: пт
Thu: чт
Wed: ср
Tue: вт
Mon: пн
ViewBookingDetails: Посмотреть детали бронирования
ReturnToHomePage: Вернуться на главную страницу
YourBookingHasBeenCreatedSuccessfully: Ваше бронирование успешно создано
Finish: Завершить
Price: Цена
Currency: Валюта
TimeZone: Часовой пояс
SourceCode: Исходный код
Resources: Ресурсы
Overview: Обзор
IssueTracking: Отслеживание ошибок
Documentation: Документация
ErDiagram: ER-диаграмма
PaymentStatus: Статус платежа
SomethingWentWrong: Что-то пошло не так
PaymentSuccessfullyCompleted: Платеж успешно завершен
PaymentIntentCancelled: Намерение платежа было отменено
Pay: Заплатить
PaymentAmount: Сумма платежа
Checkout: Оформить заказ
PayNow: Заплатить сейчас
PayAtVenue: Оплата на месте
PaymentMethod: Способ оплаты
AppointmentTime: Время встречи
BookAService: Забронировать услугу
Next: Следующий
ServicesToBook: Услуги для бронирования
MakeAnAppointment: Записаться на прием
WelcomeTo: Добро пожаловать на
TheStart: Начало
AssignmentDate: Дата назначения
ServiceAssignment: Назначение
Description: Описание
Service: Услуга
Services: Услуги
ServiceAssignments: Назначения
Employee: Сотрудник
Phone: Телефон
Mobile: Мобильный
Staff: Персонал
AlreadyExists: Уже существует
Workspace: Рабочее место
Address: Адрес
Workspaces: Рабочие места
Details: Подробности
RecordAdded: Запись добавлена
Business: Деятельность
Owner: Владелец
TheName: Наименование
Add: Добавить
YouMightWantToAddAFew: Возможно, вы захотите добавить несколько
ThereAreNoDataYet: Данных пока нет
NoDataYet: Данных пока нет
Businesses: Деятельности
Attribution: Атрибуция
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
NotSpecified: Не указано
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Dele: Удалить
Email: Электронная почта
Google: Google
No: Нет
Verified: Проверено
VerificationKey: Ключ проверки
Yes: Да
User: Пользователь
NoUsersYet: Пользователей пока нет
NotIndicated: Не указано
Birthday: День рождения
FullName: Полное имя
Cancel: Отмена
Save: Сохранить
Edit: Редактировать
Account: Учетная запись
PersonalInfo: Персональные данные
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
GoogleSecretManager: Google Secret Manager
GmailAccount: Учетная запись Gmail
Cleared: Очищено
InvalidFormData: Неверные данные формы
RecordDeleted: Запись удалена
ClearSettings: Сбросить
RecordEdited: Запись отредактирована
InvalidStoreType: Неверный тип хранилища
StoreType: Тип хранилища
Database: База данных
UserSession: Пользовательская сессия
Initialize: Инициализировать
Tokens: Токены
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
Authentication: Аутентификация
PasswordRecovery: Восстановление пароля
CreatePassword: Создание пароля
EmailVerification: Проверка электронной почты
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
JustSentEmailTo: Мы только что отправили электронное письмо на
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
DidNotGetEmail: Не получили письмо?
ResendEmail: Отправить письмо повторно
Back: Вернуться
Registration: Регистрация
Or: или
ForgotYourPassword: Забыли пароль?
DoNotHaveAnAccount: У вас нет учетной записи?
CreateAccount: Зарегистрироваться
EmailAddress: Адрес электронной почты
Password: Пароль
DemoUserAccounts: Демо-аккаунты
Superuser: Суперпользователь
Administrator: Администратор
ThankYou: Спасибо
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
SignInWithGoogle: Войти через Google
SignIn: Войти
SignOut: Выйти
UserAccount: Учетная запись
Photo: Фото
Data: Данные
MainMenu: Главное меню
Users: Пользователи
Welcome: Добро пожаловать
AppDocumentation: Документация приложения
AppDescription: Онлайн-бронирование услуг и встреч
AppName: Reservare

Doc001 appname href: <a href=#{href} target=_blank>«#{appname}»</a> позволяет компаниям регистрировать услуги и ресурсы, которые клиент может зарезервировать и/или назначить встречу.

Doc002 href: <a href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.

Doc003 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.

Doc004: Учетная запись суперпользователя определяется во время развертывания. Суперпользователь управляет другими пользователями и предоставляет или отзывает права администратора конкретным пользователям.

Doc005: Интеграция с внешними API

Doc006 href1 href2: Новый пользователь может <a href=#{href1} target=_blank>зарегистрироваться</a>, используя существующую учетную запись Google или подтвержденный адрес электронной почты. <a href=#{href2} target=_blank>API Gmail</a> используется в качестве посредника для отправки ссылок проверки в почтовый ящик пользователя.

Doc007: Пользователю может быть предоставлена роль администратора суперпользователем или другим администратором. Только пользователи с ролью администратора имеют доступ к административным данным.

Doc008 href: Для имитации успешного платежа используйте тестовые карты из <a href=#{href}>следующего списка</a>.

Doc009 href: Для имитации платежей, от которых эмитент отклоняет, используйте тестовые карты из <a href=#{href}>следующего списка</a>.

Doc010: Для каждого рабочего пространства вы можете указать один или несколько вариантов оплаты, выбрав его тип, название и платежный шлюз.

Doc011: Если для рабочего пространства настроено несколько платежных шлюзов, они будут представлены в качестве вариантов пользователю, записывающемуся на прием.

Doc012: Если для рабочего пространства настроен только один способ оплаты (платежный шлюз), то он будет использоваться по умолчанию, и, таким образом, в процессе бронирования будет на один шаг меньше.

Doc013: Для рабочего пространства необходимо указать хотя бы один вариант оплаты (платежный шлюз). Если ничего не указано, при бронировании возникнет ошибка.

Doc014: Сектор представляет собой вид деятельности предоставляемой услуги. В основном используются в качестве ключей поиска услуг.

Doc015: При необходимости может быть определена иерархия таких секторов.