
Authentication: Аутентификация
PasswordRecovery: Восстановление пароля
CreatePassword: Создание пароля
EmailVerification: Проверка электронной почты
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
JustSentEmailTo: Мы только что отправили электронное письмо на
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
DidNotGetEmail: Не получили письмо?
ResendEmail: Отправить письмо повторно
Back: Вернуться
Registration: Регистрация
Or: или
ForgotYourPassword: Забыли пароль?
DoNotHaveAnAccount: У вас нет учетной записи?
CreateAccount: Зарегистрироваться
EmailAddress: Адрес электронной почты
Password: Пароль
DemoUserAccounts: Демо-аккаунты
Superuser: Суперпользователь
Administrator: Администратор
ThankYou: Спасибо
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
SignInWithGoogle: Войти через Google
SignIn: Войти
SignOut: Выйти
UserAccount: Учетная запись
Photo: Фото
Data: Данные
MainMenu: Главное меню
Users: Пользователи
Welcome: Добро пожаловать
AppName: Reservare