PaymentStatus: Статус платежа
SomethingWentWrong: Что-то пошло не так
PaymentSuccessfullyCompleted: Платеж успешно завершен
PaymentIntentCancelled: Намерение платежа было отменено
Pay: Заплатить
PaymentAmount: Сумма платежа
Checkout: Оформить заказ
PayNow: Заплатить сейчас
PayAtVenue: Оплата на месте
PaymentMethod: Способ оплаты
AppointmentTime: Время встречи
BookAService: Забронировать услугу
Next: Следующий
ServicesToBook: Услуги для бронирования
MakeAnAppointment: Записаться на прием
WelcomeTo: Добро пожаловать на
TheStart: Начало
AssignmentDate: Дата назначения
ServiceAssignment: Назначение
Description: Описание
Service: Услуга
Services: Услуги
ServiceAssignments: Назначения
Employee: Сотрудник
Phone: Телефон
Mobile: Мобильный
Staff: Персонал
AlreadyExists: Уже существует
Workspace: Рабочее место
Address: Адрес
Workspaces: Рабочие места
Details: Подробности
RecordAdded: Запись добавлена
Business: Деятельность
Owner: Владелец
TheName: Наименование
Add: Добавить
YouMightWantToAddAFew: Возможно, вы захотите добавить несколько
ThereAreNoDataYet: Данных пока нет
NoDataYet: Данных пока нет
Businesses: Деятельности
Attribution: Атрибуция
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
NotSpecified: Не указано
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Dele: Удалить
Email: Электронная почта
Google: Google
No: Нет
Verified: Проверено
VerificationKey: Ключ проверки
Yes: Да
User: Пользователь
NoUsersYet: Пользователей пока нет
NotIndicated: Не указано
Birthday: День рождения
FullName: Полное имя
Cancel: Отмена
Save: Сохранить
Edit: Редактировать
Account: Учетная запись
PersonalInfo: Персональные данные
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
GoogleSecretManager: Google Secret Manager
GmailAccount: Учетная запись Gmail
Cleared: Очищено
InvalidFormData: Неверные данные формы
RecordDeleted: Запись удалена
ClearSettings: Сбросить
RecordEdited: Запись отредактирована
InvalidStoreType: Неверный тип хранилища
StoreType: Тип хранилища
Database: База данных
UserSession: Пользовательская сессия
Initialize: Инициализировать
Tokens: Токены
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
Authentication: Аутентификация
PasswordRecovery: Восстановление пароля
CreatePassword: Создание пароля
EmailVerification: Проверка электронной почты
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
JustSentEmailTo: Мы только что отправили электронное письмо на
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
DidNotGetEmail: Не получили письмо?
ResendEmail: Отправить письмо повторно
Back: Вернуться
Registration: Регистрация
Or: или
ForgotYourPassword: Забыли пароль?
DoNotHaveAnAccount: У вас нет учетной записи?
CreateAccount: Зарегистрироваться
EmailAddress: Адрес электронной почты
Password: Пароль
DemoUserAccounts: Демо-аккаунты
Superuser: Суперпользователь
Administrator: Администратор
ThankYou: Спасибо
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
SignInWithGoogle: Войти через Google
SignIn: Войти
SignOut: Выйти
UserAccount: Учетная запись
Photo: Фото
Data: Данные
MainMenu: Главное меню
Users: Пользователи
Welcome: Добро пожаловать
AppName: Reservare